export const resourceData = [
// Legal Aid Resources
{
  id: 'legal1',
  name: 'Community Legal Aid Center',
  category: 'legal',
  description: 'Free legal assistance for low-income individuals and families. Services include housing issues, family law, public benefits, and more.',
  logo: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 1.2,
  address: '123 Justice Ave, Anytown, ST 12345',
  phone: '(555) 123-4567',
  email: 'help@legalaid.org',
  website: 'https://example.com/legalaid',
  hours: 'Monday - Friday: 9am - 5pm',
  status: 'Open',
  isAccessible: true,
  isFree: true,
  services: ['Housing law assistance', 'Family law services', 'Public benefits advocacy', 'Consumer protection', 'Free legal clinics'],
  latitude: 40.7128,
  longitude: -74.006
}, {
  id: 'legal2',
  name: 'Justice for All Law Clinic',
  category: 'legal',
  description: 'Nonprofit organization providing legal representation and advice to underserved communities, focusing on civil rights and immigration issues.',
  logo: 'https://images.unsplash.com/photo-1521791055366-0d553872125f?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1521791055366-0d553872125f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 2.5,
  address: '456 Rights Blvd, Anytown, ST 12345',
  phone: '(555) 234-5678',
  email: 'info@justiceforall.org',
  website: 'https://example.com/justiceforall',
  hours: 'Monday - Thursday: 10am - 6pm, Friday: 10am - 4pm',
  status: 'Closed',
  isAccessible: true,
  isFree: true,
  services: ['Immigration legal services', 'Civil rights representation', 'Document preparation assistance', 'Legal consultation', 'Know your rights workshops'],
  latitude: 40.7282,
  longitude: -74.0776
},
// Food & Nutrition Resources
{
  id: 'food1',
  name: 'Community Food Bank',
  category: 'food',
  description: 'Provides emergency food assistance to individuals and families facing food insecurity. No ID required for basic services.',
  logo: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 0.8,
  address: '789 Hunger Relief Dr, Anytown, ST 12345',
  phone: '(555) 345-6789',
  email: 'help@communityfoodbank.org',
  website: 'https://example.com/foodbank',
  hours: 'Tuesday - Saturday: 10am - 3pm',
  status: 'Open',
  isAccessible: true,
  isFree: true,
  services: ['Emergency food boxes', 'Fresh produce distribution', 'SNAP application assistance', 'Community kitchen meals', 'Home delivery for seniors and disabled'],
  latitude: 40.7053,
  longitude: -74.0088
}, {
  id: 'food2',
  name: 'Meals With Love',
  category: 'food',
  description: 'Hot meal program serving nutritious lunches and dinners to anyone in need. Also offers nutrition education and cooking classes.',
  logo: 'https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 1.5,
  address: '101 Nourish St, Anytown, ST 12345',
  phone: '(555) 456-7890',
  email: 'contact@mealswithlove.org',
  website: 'https://example.com/mealswithlove',
  hours: 'Monday - Friday: 11:30am - 1:30pm, 5:30pm - 7:30pm',
  status: 'Closed',
  isAccessible: true,
  isFree: true,
  services: ['Hot lunch and dinner service', 'Nutrition education', 'Cooking classes', 'Food pantry access', "Children's meal program"],
  latitude: 40.7225,
  longitude: -73.9905
},
// Housing Assistance Resources
{
  id: 'housing1',
  name: 'Safe Haven Housing Network',
  category: 'housing',
  description: 'Emergency shelter and transitional housing programs for individuals and families experiencing homelessness or housing instability.',
  logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 2.1,
  address: '202 Shelter Way, Anytown, ST 12345',
  phone: '(555) 567-8901',
  email: 'help@safehaven.org',
  website: 'https://example.com/safehaven',
  hours: '24/7 Emergency Services',
  status: 'Open',
  isAccessible: true,
  isFree: true,
  services: ['Emergency shelter', 'Transitional housing', 'Housing search assistance', 'Rental application help', 'Eviction prevention services'],
  latitude: 40.7382,
  longitude: -73.9982
}, {
  id: 'housing2',
  name: 'Affordable Housing Coalition',
  category: 'housing',
  description: 'Helps low-income residents find and apply for affordable housing options. Provides rental assistance and housing counseling services.',
  logo: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 1.9,
  address: '303 Housing Blvd, Anytown, ST 12345',
  phone: '(555) 678-9012',
  email: 'info@affordablehousing.org',
  website: 'https://example.com/affordablehousing',
  hours: 'Monday - Friday: 9am - 4pm',
  status: 'Closed',
  isAccessible: false,
  isFree: true,
  services: ['Affordable housing listings', 'Rental assistance programs', 'First-time homebuyer education', 'Housing discrimination complaints', 'Tenant rights counseling'],
  latitude: 40.7484,
  longitude: -73.9857
},
// Healthcare Services Resources
{
  id: 'healthcare1',
  name: 'Community Health Clinic',
  category: 'healthcare',
  description: 'Provides primary healthcare services to uninsured and underinsured individuals. Sliding scale fees based on income.',
  logo: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 1.3,
  address: '404 Wellness Ave, Anytown, ST 12345',
  phone: '(555) 789-0123',
  email: 'care@communityclinic.org',
  website: 'https://example.com/communityclinic',
  hours: 'Monday - Friday: 8am - 7pm, Saturday: 9am - 1pm',
  status: 'Open',
  isAccessible: true,
  isFree: false,
  services: ['Primary care services', 'Preventive care', 'Chronic disease management', 'Basic lab services', 'Medication assistance program'],
  nextAvailable: 'Today at 3:30pm',
  latitude: 40.7093,
  longitude: -74.0167
}, {
  id: 'healthcare2',
  name: 'Mental Health Access Center',
  category: 'healthcare',
  description: 'Offers mental health services including counseling, crisis intervention, and support groups. Telehealth options available.',
  logo: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 2.7,
  address: '505 Mindful St, Anytown, ST 12345',
  phone: '(555) 890-1234',
  email: 'help@mentalhealthaccess.org',
  website: 'https://example.com/mentalhealth',
  hours: 'Monday - Thursday: 9am - 8pm, Friday: 9am - 5pm',
  status: 'Closed',
  isAccessible: true,
  isFree: false,
  services: ['Individual counseling', 'Group therapy sessions', 'Crisis intervention', 'Telehealth appointments', 'Medication management'],
  nextAvailable: 'Tomorrow at 10:15am',
  latitude: 40.7589,
  longitude: -73.9851
},
// Employment Help Resources
{
  id: 'employment1',
  name: 'Career Development Center',
  category: 'employment',
  description: 'Offers job search assistance, resume writing, interview preparation, and career counseling services for job seekers.',
  logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 1.7,
  address: '606 Career Path, Anytown, ST 12345',
  phone: '(555) 901-2345',
  email: 'jobs@careercenter.org',
  website: 'https://example.com/careercenter',
  hours: 'Monday - Friday: 8:30am - 5pm',
  status: 'Open',
  isAccessible: true,
  isFree: true,
  services: ['Resume and cover letter help', 'Job search assistance', 'Interview preparation', 'Career counseling', 'Computer lab access'],
  latitude: 40.7127,
  longitude: -74.0134
}, {
  id: 'employment2',
  name: 'Workforce Training Institute',
  category: 'employment',
  description: 'Provides vocational training, certification programs, and job placement services for various industries and skill levels.',
  logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 3.2,
  address: '707 Skills Ave, Anytown, ST 12345',
  phone: '(555) 012-3456',
  email: 'training@workforceinstitute.org',
  website: 'https://example.com/workforcetraining',
  hours: 'Monday - Thursday: 9am - 7pm, Friday: 9am - 5pm',
  status: 'Closed',
  isAccessible: true,
  isFree: false,
  services: ['Vocational skills training', 'Industry certifications', 'Job placement services', 'Apprenticeship programs', 'Digital literacy classes'],
  latitude: 40.7223,
  longitude: -74.0027
},
// Disability Services Resources
{
  id: 'disability1',
  name: 'Accessible Living Center',
  category: 'disability',
  description: 'Provides resources and support services for people with disabilities to live independently in their communities.',
  logo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 2.4,
  address: '808 Access Way, Anytown, ST 12345',
  phone: '(555) 123-4567',
  email: 'info@accessibleliving.org',
  website: 'https://example.com/accessibleliving',
  hours: 'Monday - Friday: 9am - 5pm',
  status: 'Open',
  isAccessible: true,
  isFree: true,
  services: ['Independent living skills training', 'Assistive technology resources', 'Accessibility evaluations', 'Peer support programs', 'Advocacy services'],
  latitude: 40.7431,
  longitude: -73.9712
}, {
  id: 'disability2',
  name: 'Disability Rights Network',
  category: 'disability',
  description: 'Advocates for the civil rights of people with disabilities through legal representation, education, and policy initiatives.',
  logo: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80',
  image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  distance: 3.5,
  address: '909 Equality Blvd, Anytown, ST 12345',
  phone: '(555) 234-5678',
  email: 'rights@disabilitynetwork.org',
  website: 'https://example.com/disabilityrights',
  hours: 'Monday - Thursday: 9am - 6pm, Friday: 9am - 4pm',
  status: 'Closed',
  isAccessible: true,
  isFree: true,
  services: ['Legal representation', 'ADA compliance assistance', 'Self-advocacy training', 'Educational rights support', 'Employment discrimination cases'],
  latitude: 40.7539,
  longitude: -73.9677
}];